apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Tensure
  description: Tensure Organization
spec:
  type: organization
  picture: https://storage.googleapis.com/backstage-images-tensure/tensureio_logo.jpeg
  profile:
    email: support@tensure.io
  children: [Cloud]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Cloud
  description: Cloud Team
spec:
  type: team
  profile:
    email: cloud@tensure.io
  parent: Tensure
  children: []
  members: [vamsi,joe]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Software
spec:
  type: team
  profile:
    email: software@tensure.io
  parent: Tensure
  children: []
  members: [vamsi]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vamsi
spec:
  profile:
    displayName: Vamsi krishna
    email: vamsi.krishna@tensure.io
  memberOf: [cloud]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vamsii
spec:
  profile:
    displayName: Vamsi Test
    email: vamsi@ioinfo.shop
  memberOf: [cloud]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: test1
spec:
  profile:
    displayName: test1
    email: test1@ioinfo.shop
  memberOf: [cloud]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: test2
spec:
  profile:
    displayName: test2
    email: test2@ioinfo.shop
  memberOf: [cloud]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: test3
spec:
  profile:
    displayName: test3
    email: test3@ioinfo.shop
  memberOf: [cloud]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Joe
spec:
  profile:
    displayName: Joe Kerstanoff
    email: joe@tensure.io
  memberOf: [cloud]