apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vamsi
spec:
  profile:
    # Intentional no displayName for testing
    displayName: Vamsi krishna
    email: vamsi.krishna@tensure.io
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [development]