apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    backstage.io/kubernetes-id: {{ include "backstage.fullname" . }}
  name: {{ include "backstage.fullname" . }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backstage.name" . }}
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: {{ include "backstage.fullname" . }}
        app: {{ include "backstage.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BACKSTAGE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.db.name }}
                  key: {{ .Values.secrets.db.key }}
            - name: BACKSTAGE_DB_CLOUD_SQL_IP
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.sql.name }}
                  key: {{ .Values.secrets.sql.key }}
            - name: BACKSTAGE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.loginid.name }}
                  key: {{ .Values.secrets.loginid.key }}
            - name: BACKSTAGE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.loginsecret.name }}
                  key: {{ .Values.secrets.loginsecret.key }}
            - name: BACKSTAGE_BACKEND_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.backendauth.name }}
                  key: {{ .Values.secrets.backendauth.key }}
            - name: BACKSTAGE_GITHUB_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.github.name }}
                  key: {{ .Values.secrets.github.key }}
            - name: BACKSTAGE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.backstage_host.name }}
                  key: {{ .Values.secrets.backstage_host.key }}
            - name: BACKSTAGE_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.github_client_id.name }}
                  key: {{ .Values.secrets.github_client_id.key }}
            - name: BACKSTAGE_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.github_client_secret.name }}
                  key: {{ .Values.secrets.github_client_secret.key }}
            - name: ARGO_CD_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.argocd_host.name }}
                  key: {{ .Values.secrets.argocd_host.key }}
            - name: ARGOCD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.argocd_token.name }}
                  key: {{ .Values.secrets.argocd_token.key }}
            - name: GRAFANA_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.grafana_host.name }}
                  key: {{ .Values.secrets.grafana_host.key }}
            - name: GRAFANA_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.grafana_token.name }}
                  key: {{ .Values.secrets.grafana_token.key }}
            - name: TECHDOCS_GCS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.techdocs_gcs_bucket.name }}
                  key: {{ .Values.secrets.techdocs_gcs_bucket.key }}
            