apiVersion: v1
kind: Service
metadata:
  labels:
    backstage.io/kubernetes-id: {{ include "backstage.fullname" . }}
  name: {{ include "backstage.fullname" . }}-service
spec:
  selector:
    app: {{ include "backstage.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
