name: Sample Workflow

permissions:
  contents: read
  pages: write
  id-token: write 
  
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin